version: '3.8'

services:
  app:
    # Build the Flask application from the current directory
    build: . 
    # Command to run Flask
    command: ./entrypoint.sh 

    ports:
    # Expose flask port to host
      - "5000:5000" 
    environment:
      DB_NAME: testDB 
  nginx:
    image: nginx:latest

    ports:
      - "80:80"
      
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app